name: Publish main branch

on:
    push:
        branches: [ main ]

jobs:
    deploy:
        uses: ./.github/workflows/publish_blog.yml
        with:
            domain_name: notmyfoo.io
        secrets:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
